# test
# nothing here

Settings:
  # use or not confirmation for command
  use-confirmation: true

JoinMessage:
  Enabled: true
  Centered: true
  Message:
    - ' '
    - '&e%player% &aJoin &bthe server!'
    - ' '

QuitMessage:
  Enabled: true
  Centered: true
  Message:
    - ' '
    - '&e%player% &cQuit &bthe server!'
    - ' '
