name: UniverseCore
version: ${project.version}
main: id.universenetwork.universecore.Bukkit.UniverseCore
api-version: 1.16
authors: [ rajaopak ]
description: UniverseCore plugin for UniverseNetwork
website: https://universenetwork.id/

permissions:
  universenetwork.gamemode.*:
    default: op
    children:
      universenetwork.gamemode.creative: true
      universenetwork.gamemode.survival: true
      universenetwork.gamemode.adventure: true
      universenetwork.gamemode.spectator: true
      universenetwork.gamemode.creative.others: true
      universenetwork.gamemode.survival.others: true
      universenetwork.gamemode.adventure.others: true
      universenetwork.gamemode.spectator.others: true
