name: UniverseCore
version: ${project.version}
main: id.universenetwork.universecore.UniverseCore
api-version: 1.16
authors: [ rajaopak ]
description: UniverseCore plugin for UniverseNetwork
website: https://universenetwork.id/
commands:
  universe:
    aliases: [uni]
  kaboom:
    aliases: [boom, ukaboom, uboom]
  santet:
    aliases: [usantet]
  whereis:
    aliases: [whereis, uwhereis, uwis, wis]
  toggledrop:
    aliases: [td, utd, utoggledrop]
  ping:
    aliases: [uping]
