name: UniverseCore
version: ${project.version}
main: id.universenetwork.universecore.Bukkit.UniverseCore
api-version: 1.16
authors: [ rajaopak ]
description: UniverseCore plugin for UniverseNetwork
website: https://universenetwork.id/
